base_url = "https://sgt.hootr.club"
title = "steen's burrow"
description = "steen's online burrow"
author = "steen"
default_language = "en-us"

compile_sass = false
build_search_index = false
minify_html = true

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

taxonomies = [{ name = "tags", feed = true }]

[markdown]
render_emoji = false
smart_punctuation = false
external_links_class = "external-link"
external_links_no_follow = true
external_links_no_referrer = true

[markdown.highlighting]
theme = "nord"
error_on_missing_language = true

[extra]
